interface ICode<T = string> {
	code: number;
	message: string;
	type: T;
}
type IErrors<T extends string | symbol | number = string> = Record<T, ICode<T>>;
// exit codes
type IExitCodes =
	| "SUCCESS"
	| "ERROR_GENERIC"
	| "ERROR_INVALID_INPUT"
	| "ERROR_FILE_NOT_FOUND"
	| "ERROR_DATABASE_CONNECTION"
	| "ERROR_DATABASE_DISCONNECTED"
	| "ERROR_COULDNT_READ_FILE"
	| "ENV_ERROR_COULDNT_FIND_FIELD"
	| "COULDNT_LOAD_ROLES"
	| "EMAIL_ERROR_GENERIC"
	| "GOOGLE_CLOUD_STORAGE_ERROR_GENERIC";

// http status codes
type IHttpStatusCodes =
	| "Continue"
	| "SwitchingProtocols"
	| "Processing"
	| "EarlyHints"
	| "OK"
	| "Created"
	| "Accepted"
	| "NonAuthoritativeInformation"
	| "NoContent"
	| "ResetContent"
	| "PartialContent"
	| "MultiStatus"
	| "AlreadyReported"
	| "IMUsed"
	| "MultipleChoices"
	| "MovedPermanently"
	| "Found"
	| "SeeOther"
	| "NotModified"
	| "TemporaryRedirect"
	| "PermanentRedirect"
	| "BadRequest"
	| "Unauthorized"
	| "PaymentRequired"
	| "Forbidden"
	| "NotFound"
	| "MethodNotAllowed"
	| "NotAcceptable"
	| "ProxyAuthenticationRequired"
	| "RequestTimeout"
	| "Conflict"
	| "Gone"
	| "LengthRequired"
	| "PreconditionFailed"
	| "PayloadTooLarge"
	| "URITooLong"
	| "UnsupportedMediaType"
	| "RangeNotSatisfiable"
	| "ExpectationFailed"
	| "ImATeapot"
	| "MisdirectedRequest"
	| "UnprocessableEntity"
	| "Locked"
	| "FailedDependency"
	| "UpgradeRequired"
	| "PreconditionRequired"
	| "TooManyRequests"
	| "RequestHeaderFieldsTooLarge"
	| "UnavailableForLegalReasons"
	| "InternalServerError"
	| "NotImplemented"
	| "BadGateway"
	| "ServiceUnavailable"
	| "GatewayTimeout"
	| "HTTPVersionNotSupported"
	| "VariantAlsoNegotiates"
	| "InsufficientStorage"
	| "LoopDetected"
	| "NotExtended"
	| "NetworkAuthenticationRequired";


